/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type LocationBlock = {
  _type: "locationBlock";
  title?: string;
  text?: string;
};

export type BrandsBlock = {
  _type: "brandsBlock";
  title?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  };
  brandLabel?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    name?: string;
    _type: "brandLabel";
    _key: string;
  }>;
};

export type BookingBlock = {
  _type: "bookingBlock";
  title?: string;
  enquiryDescription?: string;
  contactDescription?: string;
  pricingDescription?: string;
  generalEnquiries?: {
    email?: string;
    phone?: string;
  };
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
};

export type ServicesBlock = {
  _type: "servicesBlock";
  title?: string;
  capabilities?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    name?: string;
    specialties?: Array<string>;
    description?: string;
    _type: "capabilities";
    _key: string;
  }>;
};

export type FullScreenHeaderImage = {
  _type: "fullScreenHeaderImage";
  title?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  };
  description?: string;
};

export type VideoCaseStudy = {
  _type: "videoCaseStudy";
  title?: string;
  projectName?: string;
  description?: string;
  client?: string;
  industry?: string;
  location?: string;
  video?: MuxVideo;
};

export type SinglePortrait = {
  _type: "singlePortrait";
  title?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  };
};

export type Landscape = {
  _type: "landscape";
  title?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  };
};

export type ImageLargeRight = {
  _type: "imageLargeRight";
  title?: string;
  leftImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  };
  rightImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  };
};

export type ImageLargeLeft = {
  _type: "imageLargeLeft";
  title?: string;
  leftImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  };
  rightImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  };
};

export type DoublePortrait = {
  _type: "doublePortrait";
  title?: string;
  leftImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  };
  rightImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  };
};

export type OfferingsModule = {
  _type: "offeringsModule";
  title?: string;
  services?: Array<{
    name?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    description?: string;
    _type: "service";
    _key: string;
  }>;
};

export type LandingModule = {
  _type: "landingModule";
  title?: string;
  video?: MuxVideo;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  };
};

export type CaseStudy = {
  _type: "caseStudy";
  title?: string;
  caseStudies?: Array<{
    client?: string;
    services?: string;
    industry?: string;
    location?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    description?: string;
    _type: "caseStudies";
    _key: string;
  }>;
};

export type BrandModule = {
  _type: "brandModule";
  title?: string;
  brands?: Array<{
    name?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    description?: string;
    _type: "brands";
    _key: string;
  }>;
};

export type LargeText = {
  _type: "largeText";
  title?: string;
  text?: string;
};

export type LargeImage = {
  _type: "largeImage";
  title?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  };
  text?: string;
};

export type FullBleed = {
  _type: "fullBleed";
  title?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  };
  text?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  defaultDescription?: string;
  defaultImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  favicon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  metaKeywords?: Array<string>;
};

export type FooterSettings = {
  _id: string;
  _type: "footerSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  phoneNumber?: string;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  copyright?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: Array<{
    _key: string;
  } & BrandModule | {
    _key: string;
  } & CaseStudy | {
    _key: string;
  } & FullBleed | {
    _key: string;
  } & LandingModule | {
    _key: string;
  } & LargeImage | {
    _key: string;
  } & LargeText | {
    _key: string;
  } & OfferingsModule | {
    _key: string;
  } & DoublePortrait | {
    _key: string;
  } & ImageLargeLeft | {
    _key: string;
  } & ImageLargeRight | {
    _key: string;
  } & Landscape | {
    _key: string;
  } & SinglePortrait | {
    _key: string;
  } & VideoCaseStudy | {
    _key: string;
  } & FullScreenHeaderImage | {
    _key: string;
  } & ServicesBlock | {
    _key: string;
  } & BookingBlock | {
    _key: string;
  } & BrandsBlock | {
    _key: string;
  } & LocationBlock>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type PageBuilder = Array<{
  _key: string;
} & BrandModule | {
  _key: string;
} & CaseStudy | {
  _key: string;
} & FullBleed | {
  _key: string;
} & LandingModule | {
  _key: string;
} & LargeImage | {
  _key: string;
} & LargeText | {
  _key: string;
} & OfferingsModule | {
  _key: string;
} & DoublePortrait | {
  _key: string;
} & ImageLargeLeft | {
  _key: string;
} & ImageLargeRight | {
  _key: string;
} & Landscape | {
  _key: string;
} & SinglePortrait | {
  _key: string;
} & VideoCaseStudy | {
  _key: string;
} & FullScreenHeaderImage | {
  _key: string;
} & ServicesBlock | {
  _key: string;
} & BookingBlock | {
  _key: string;
} & BrandsBlock | {
  _key: string;
} & LocationBlock>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type MuxVideo = {
  _type: "mux.video";
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "mux.videoAsset";
  };
};

export type MuxVideoAsset = {
  _id: string;
  _type: "mux.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: string;
  assetId?: string;
  playbackId?: string;
  filename?: string;
  thumbTime?: number;
  data?: MuxAssetData;
};

export type MuxAssetData = {
  _type: "mux.assetData";
  resolution_tier?: string;
  upload_id?: string;
  created_at?: string;
  id?: string;
  status?: string;
  max_stored_resolution?: string;
  passthrough?: string;
  encoding_tier?: string;
  master_access?: string;
  aspect_ratio?: string;
  duration?: number;
  max_stored_frame_rate?: number;
  mp4_support?: string;
  max_resolution_tier?: string;
  tracks?: Array<{
    _key: string;
  } & MuxTrack>;
  playback_ids?: Array<{
    _key: string;
  } & MuxPlaybackId>;
  static_renditions?: MuxStaticRenditions;
};

export type MuxStaticRenditions = {
  _type: "mux.staticRenditions";
  status?: string;
  files?: Array<{
    _key: string;
  } & MuxStaticRenditionFile>;
};

export type MuxStaticRenditionFile = {
  _type: "mux.staticRenditionFile";
  ext?: string;
  name?: string;
  width?: number;
  bitrate?: number;
  filesize?: number;
  height?: number;
};

export type MuxPlaybackId = {
  _type: "mux.playbackId";
  id?: string;
  policy?: string;
};

export type MuxTrack = {
  _type: "mux.track";
  id?: string;
  type?: string;
  max_width?: number;
  max_frame_rate?: number;
  duration?: number;
  max_height?: number;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityFileAsset | Geopoint | LocationBlock | BrandsBlock | BookingBlock | ServicesBlock | FullScreenHeaderImage | VideoCaseStudy | SinglePortrait | Landscape | ImageLargeRight | ImageLargeLeft | DoublePortrait | OfferingsModule | LandingModule | CaseStudy | BrandModule | LargeText | LargeImage | FullBleed | SiteSettings | FooterSettings | Page | Slug | PageBuilder | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata | MuxVideo | MuxVideoAsset | MuxAssetData | MuxStaticRenditions | MuxStaticRenditionFile | MuxPlaybackId | MuxTrack;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries.tsx
// Variable: HOME_QUERY
// Query: *[_type == "page" && slug.current == "home"][0]{    ...,    content[] {      _key,      _type,      ...,      video {        asset-> {          playbackId,          assetId,          filename        }      },      services[] {         name,        description,        image {          asset-> { url },          caption,          alt        }      },      caseStudies[] {        client,        services,        industry,        location,        image {          asset-> { url },          caption,          alt        }      },      brands[] {        name,        image {          asset-> { url },          caption,          alt        },        description      },      capabilities[] {        _type,        ...,        image {          asset-> { url },          caption,          alt        },        name,        specialties,        description      }    }  }
export type HOME_QUERYResult = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content: Array<{
    _key: string;
    _type: "bookingBlock";
    title?: string;
    enquiryDescription?: string;
    contactDescription?: string;
    pricingDescription?: string;
    generalEnquiries?: {
      email?: string;
      phone?: string;
    };
    socialLinks?: Array<{
      platform?: string;
      url?: string;
      _type: "socialLink";
      _key: string;
    }>;
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "brandModule";
    title?: string;
    brands: Array<{
      name: string | null;
      image: {
        asset: {
          url: string | null;
        } | null;
        caption: string | null;
        alt: string | null;
      } | null;
      description: string | null;
    }> | null;
    video: null;
    services: null;
    caseStudies: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "brandsBlock";
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    brandLabel?: Array<{
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        alt?: string;
        _type: "image";
      };
      name?: string;
      _type: "brandLabel";
      _key: string;
    }>;
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "caseStudy";
    title?: string;
    caseStudies: Array<{
      client: string | null;
      services: string | null;
      industry: string | null;
      location: string | null;
      image: {
        asset: {
          url: string | null;
        } | null;
        caption: string | null;
        alt: string | null;
      } | null;
    }> | null;
    video: null;
    services: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "doublePortrait";
    title?: string;
    leftImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    rightImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "fullBleed";
    title?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    text?: string;
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "fullScreenHeaderImage";
    title?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    description?: string;
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "imageLargeLeft";
    title?: string;
    leftImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    rightImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "imageLargeRight";
    title?: string;
    leftImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    rightImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "landingModule";
    title?: string;
    video: {
      asset: {
        playbackId: string | null;
        assetId: string | null;
        filename: string | null;
      } | null;
    } | null;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "landscape";
    title?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "largeImage";
    title?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    text?: string;
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "largeText";
    title?: string;
    text?: string;
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "locationBlock";
    title?: string;
    text?: string;
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "offeringsModule";
    title?: string;
    services: Array<{
      name: string | null;
      description: string | null;
      image: {
        asset: {
          url: string | null;
        } | null;
        caption: string | null;
        alt: string | null;
      } | null;
    }> | null;
    video: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "servicesBlock";
    title?: string;
    capabilities: Array<{
      _type: "capabilities";
      image: {
        asset: {
          url: string | null;
        } | null;
        caption: string | null;
        alt: string | null;
      } | null;
      name: string | null;
      specialties: Array<string> | null;
      description: string | null;
      _key: string;
    }> | null;
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
  } | {
    _key: string;
    _type: "singlePortrait";
    title?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "videoCaseStudy";
    title?: string;
    projectName?: string;
    description?: string;
    client?: string;
    industry?: string;
    location?: string;
    video: {
      asset: {
        playbackId: string | null;
        assetId: string | null;
        filename: string | null;
      } | null;
    } | null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  }> | null;
} | null;
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    ...,    content[] {      _key,      _type,      ...,      video {        asset-> {          playbackId,          assetId,          filename        }      },      services[] {         name,        description,        image {          asset-> { url },          caption,          alt        }      },      caseStudies[] {        client,        services,        industry,        location,        image {          asset-> { url },          caption,          alt        }      },      brands[] {        name,        image {          asset-> { url },          caption,          alt        },        description      },      capabilities[] {        _type,        ...,        image {          asset-> { url },          caption,          alt        },        name,        specialties,        description      }    }  }
export type PAGE_QUERYResult = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content: Array<{
    _key: string;
    _type: "bookingBlock";
    title?: string;
    enquiryDescription?: string;
    contactDescription?: string;
    pricingDescription?: string;
    generalEnquiries?: {
      email?: string;
      phone?: string;
    };
    socialLinks?: Array<{
      platform?: string;
      url?: string;
      _type: "socialLink";
      _key: string;
    }>;
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "brandModule";
    title?: string;
    brands: Array<{
      name: string | null;
      image: {
        asset: {
          url: string | null;
        } | null;
        caption: string | null;
        alt: string | null;
      } | null;
      description: string | null;
    }> | null;
    video: null;
    services: null;
    caseStudies: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "brandsBlock";
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    brandLabel?: Array<{
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        alt?: string;
        _type: "image";
      };
      name?: string;
      _type: "brandLabel";
      _key: string;
    }>;
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "caseStudy";
    title?: string;
    caseStudies: Array<{
      client: string | null;
      services: string | null;
      industry: string | null;
      location: string | null;
      image: {
        asset: {
          url: string | null;
        } | null;
        caption: string | null;
        alt: string | null;
      } | null;
    }> | null;
    video: null;
    services: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "doublePortrait";
    title?: string;
    leftImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    rightImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "fullBleed";
    title?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    text?: string;
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "fullScreenHeaderImage";
    title?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    description?: string;
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "imageLargeLeft";
    title?: string;
    leftImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    rightImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "imageLargeRight";
    title?: string;
    leftImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    rightImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "landingModule";
    title?: string;
    video: {
      asset: {
        playbackId: string | null;
        assetId: string | null;
        filename: string | null;
      } | null;
    } | null;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "landscape";
    title?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "largeImage";
    title?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    text?: string;
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "largeText";
    title?: string;
    text?: string;
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "locationBlock";
    title?: string;
    text?: string;
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "offeringsModule";
    title?: string;
    services: Array<{
      name: string | null;
      description: string | null;
      image: {
        asset: {
          url: string | null;
        } | null;
        caption: string | null;
        alt: string | null;
      } | null;
    }> | null;
    video: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "servicesBlock";
    title?: string;
    capabilities: Array<{
      _type: "capabilities";
      image: {
        asset: {
          url: string | null;
        } | null;
        caption: string | null;
        alt: string | null;
      } | null;
      name: string | null;
      specialties: Array<string> | null;
      description: string | null;
      _key: string;
    }> | null;
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
  } | {
    _key: string;
    _type: "singlePortrait";
    title?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    };
    video: null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  } | {
    _key: string;
    _type: "videoCaseStudy";
    title?: string;
    projectName?: string;
    description?: string;
    client?: string;
    industry?: string;
    location?: string;
    video: {
      asset: {
        playbackId: string | null;
        assetId: string | null;
        filename: string | null;
      } | null;
    } | null;
    services: null;
    caseStudies: null;
    brands: null;
    capabilities: null;
  }> | null;
} | null;
// Variable: NAVIGATION_QUERY
// Query: *[_type == "page" && defined(slug.current)]{    "title": title,    "slug": slug.current  }
export type NAVIGATION_QUERYResult = Array<{
  title: string | null;
  slug: string | null;
}>;
// Variable: FOOTER_SETTINGS
// Query: *[_type == "footerSettings"][0]{    email,    phoneNumber,    socialLinks,    copyright  }
export type FOOTER_SETTINGSResult = {
  email: string | null;
  phoneNumber: string | null;
  socialLinks: Array<{
    platform?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }> | null;
  copyright: string | null;
} | null;
// Variable: SITE_SETTINGS
// Query: *[_type == "siteSettings"][0]{    siteTitle,    defaultDescription,    metaKeywords,    favicon {      asset->{        url      }    },    defaultImage {      asset->{        url      }    }  }
export type SITE_SETTINGSResult = {
  siteTitle: string | null;
  defaultDescription: string | null;
  metaKeywords: Array<string> | null;
  favicon: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  defaultImage: {
    asset: {
      url: string | null;
    } | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"page\" && slug.current == \"home\"][0]{\n    ...,\n    content[] {\n      _key,\n      _type,\n      ...,\n      video {\n        asset-> {\n          playbackId,\n          assetId,\n          filename\n        }\n      },\n      services[] { \n        name,\n        description,\n        image {\n          asset-> { url },\n          caption,\n          alt\n        }\n      },\n      caseStudies[] {\n        client,\n        services,\n        industry,\n        location,\n        image {\n          asset-> { url },\n          caption,\n          alt\n        }\n      },\n      brands[] {\n        name,\n        image {\n          asset-> { url },\n          caption,\n          alt\n        },\n        description\n      },\n      capabilities[] {\n        _type,\n        ...,\n        image {\n          asset-> { url },\n          caption,\n          alt\n        },\n        name,\n        specialties,\n        description\n      }\n    }\n  }\n": HOME_QUERYResult;
    "\n  *[_type == \"page\" && slug.current == $slug][0]{\n    ...,\n    content[] {\n      _key,\n      _type,\n      ...,\n      video {\n        asset-> {\n          playbackId,\n          assetId,\n          filename\n        }\n      },\n      services[] { \n        name,\n        description,\n        image {\n          asset-> { url },\n          caption,\n          alt\n        }\n      },\n      caseStudies[] {\n        client,\n        services,\n        industry,\n        location,\n        image {\n          asset-> { url },\n          caption,\n          alt\n        }\n      },\n      brands[] {\n        name,\n        image {\n          asset-> { url },\n          caption,\n          alt\n        },\n        description\n      },\n      capabilities[] {\n        _type,\n        ...,\n        image {\n          asset-> { url },\n          caption,\n          alt\n        },\n        name,\n        specialties,\n        description\n      }\n    }\n  }\n": PAGE_QUERYResult;
    "\n  *[_type == \"page\" && defined(slug.current)]{\n    \"title\": title,\n    \"slug\": slug.current\n  }\n": NAVIGATION_QUERYResult;
    "\n  *[_type == \"footerSettings\"][0]{\n    email,\n    phoneNumber,\n    socialLinks,\n    copyright\n  }\n": FOOTER_SETTINGSResult;
    "\n  *[_type == \"siteSettings\"][0]{\n    siteTitle,\n    defaultDescription,\n    metaKeywords,\n    favicon {\n      asset->{\n        url\n      }\n    },\n    defaultImage {\n      asset->{\n        url\n      }\n    }\n  }\n": SITE_SETTINGSResult;
  }
}
